core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('home.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('rendas/', include('renda.urls')),
    path('investimentos/', include('investimento.urls')),
    path('gastos/', include('gasto.urls')),
    path('admin/', admin.site.urls),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='index'),
    path('visao_geral/', views.VisaoGeralView.as_view(), name='visao_geral'),
    path(
        'visao_geral/mes_seguinte/',
        views.VisaoGeralProxMesView.as_view(),
        name='visao_geral_prox_mes'
    ),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.shortcuts import render
from django.utils import timezone
from django.views import View

from gasto.models import Gasto
from gasto.selectors import (get_aggregations_gastos, get_annotations_gastos,
                             get_gastos_by_user)
from investimento.models import Investimento
from investimento.selectors import (get_aggregations_investimentos,
                                    get_annotations_investimentos,
                                    get_investimentos_by_user)
from renda.models import Renda
from renda.selectors import (get_aggregations_rendas, get_annotations_rendas,
                             get_rendas_by_user)


class DashboardView(LoginRequiredMixin, View):
    login_url = "home:login"

    def get(self, request):
        rendas = Renda.objects.filter(
            owner=request.user
        ).select_related(
            'tipo'
        )
        total_rendas = rendas.aggregate(total=Sum('valor'))
        # agreggations_per_year = get_aggregations_rendas_por_ano(rendas)

        investimentos = Investimento.objects.filter(
            owner=request.user
        ).select_related(
            'tipo'
        )
        total_investimentos = investimentos.aggregate(total=Sum('valor'))

        gastos = Gasto.objects.filter(
            owner=request.user
        ).select_related(
            'tipo', 'categoria'
        )
        total_gastos = gastos.aggregate(total=Sum('valor'))

        try:
            sem_lancamento = total_rendas.get(
                'total') - total_gastos.get('total') - total_investimentos.get('total')  # noqa
        except TypeError:
            sem_lancamento = total_rendas.get('total') - 0

        ctx = {
            'rendas': rendas,
            'total_rendas': total_rendas,
            'investimentos': investimentos,
            'total_investimentos': total_investimentos,
            'gastos': gastos,
            'total_gastos': total_gastos,
            'sem_lancamento': sem_lancamento
        }
        return render(request, 'dashboard/pages/dashboard.html', ctx)


class VisaoGeralView(LoginRequiredMixin, View):
    login_url = "home:login"

    def get(self, request):
        now = timezone.now()
        mes_atual = now.month
        ano_atual = now.year

        rendas_do_mes = get_rendas_by_user(request).filter(
            data__month=mes_atual, data__year=ano_atual
        )
        investimentos_do_mes = get_investimentos_by_user(request).filter(
            data__month=mes_atual, data__year=ano_atual
        )
        gastos_do_mes = get_gastos_by_user(request).filter(
            data__month=mes_atual, data__year=ano_atual
        )

        # * Aggregations
        agr_rendas = get_aggregations_rendas(rendas_do_mes)
        agr_invest = get_aggregations_investimentos(investimentos_do_mes)
        agr_gastos = get_aggregations_gastos(gastos_do_mes)

        # * Annotations
        ann_rendas = get_annotations_rendas(rendas_do_mes)
        ann_invest = get_annotations_investimentos(investimentos_do_mes)
        ann_gastos = get_annotations_gastos(gastos_do_mes)

        try:
            sem_lancamento = agr_rendas.get(
                'total') - agr_gastos.get('total') - agr_invest.get('total')  # noqa
        except TypeError:
            sem_lancamento = agr_rendas.get('total') - 0

        ctx = {
            'gastos_do_mes': gastos_do_mes,
            'total_rendas': agr_rendas,
            'total_investimentos': agr_invest,
            'total_gastos': agr_gastos,
            'sem_lancamento': sem_lancamento,
            'annotations_rendas': ann_rendas,
            'annotations_invest': ann_invest,
            'annotations_gastos': ann_gastos
        }

        return render(request, 'dashboard/pages/visao_geral.html', ctx)


class VisaoGeralProxMesView(LoginRequiredMixin, View):
    login_url = "home:login"

    def get(self, request):
        now = timezone.now()
        mes_atual = now.month
        if mes_atual == 12:
            mes_atual = 1
        else:
            mes_atual += 1
        ano_atual = now.year + 1

        rendas_do_mes = get_rendas_by_user(request).filter(
            data__month=mes_atual, data__year=ano_atual
        )
        investimentos_do_mes = get_investimentos_by_user(request).filter(
            data__month=mes_atual, data__year=ano_atual
        )
        gastos_do_mes = get_gastos_by_user(request).filter(
            data__month=mes_atual, data__year=ano_atual
        )

        # * Aggregations
        agr_rendas = get_aggregations_rendas(rendas_do_mes)
        agr_invest = get_aggregations_investimentos(investimentos_do_mes)
        agr_gastos = get_aggregations_gastos(gastos_do_mes)

        # * Annotations
        ann_rendas = get_annotations_rendas(rendas_do_mes)
        ann_invest = get_annotations_investimentos(investimentos_do_mes)
        ann_gastos = get_annotations_gastos(gastos_do_mes)

        try:
            sem_lancamento = agr_rendas.get(
                'total') - agr_gastos.get('total') - agr_invest.get('total')  # noqa
        except TypeError:
            sem_lancamento = agr_rendas.get('total') - 0

        ctx = {
            'mes': mes_atual,
            'ano': ano_atual,
            'gastos_do_mes': gastos_do_mes,
            'total_rendas': agr_rendas,
            'total_investimentos': agr_invest,
            'total_gastos': agr_gastos,
            'sem_lancamento': sem_lancamento,
            'annotations_rendas': ann_rendas,
            'annotations_invest': ann_invest,
            'annotations_gastos': ann_gastos
        }

        return render(
            request,
            'dashboard/pages/visao_geral_prox_mes.html',
            ctx
        )

dashboard/templates/dashboard/pages/dashboard.html
{% extends 'global/base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock title %}
{% block content %}
<section class="content">
    <div class="content_header">
        <h1 class="title_hero">Dashboard</h1>
        {% include "global/partials/messages.html" %}
    </div>
    <div class="cards">
        <div class="card rendas">
            <h3>Rendas</h3>
            <span><i class="bi bi-cash-stack"></i> R$ {{ total_rendas.total }}</span>
        </div>
        <div class="card investimentos">
            <h3>Investimentos</h3>
            <span><i class="bi bi-graph-up"></i> R$ {{ total_investimentos.total }}</span>
        </div>
        <div class="card gastos">
            <h3>Gastos</h3>
            <span><i class="bi bi-credit-card-fill"></i> R$ {{ total_gastos.total }}</span>
        </div>
        <div class="card sem-track">
            <h3>Sem Lançamento</h3>
            <span><i class="bi bi-question-circle-fill"></i> R$ {{ sem_lancamento }}</span>
        </div>
    </div>
    <div class="charts">
        <div class="chart">
            <canvas id="myChart"></canvas>
        </div>
        <div class="chart">
            <canvas id="myChart2"></canvas>
        </div>
        <div class="chart">
            <canvas id="myChart3"></canvas>
        </div>
        <div class="chart">
            <canvas id="myChart4"></canvas>
        </div>
    </div>
</section>
{% endblock content %}
{% block scripts %}
<script src="{% static 'global/js/chart_line_mychart1.js' %}"></script>
<script src="{% static 'global/js/chart_bar_mychart2.js' %}"></script>
<script src="{% static 'global/js/chart_bar_mychart3.js' %}"></script>
<script src="{% static 'global/js/chart_bar_mychart4.js' %}"></script>
<script src="{% static 'global/js/filter.js' %}"></script>
{% endblock scripts %}

dashboard/templates/dashboard/pages/visao_geral.html
{% extends 'global/base.html' %}
{% load static %}
{% block title %}Visão Geral{% endblock title %}
{% block content %}
<section class="content_vg">
    <div class="content_header">
        <h1 class="title_hero">Visão geral - Mês Atual</h1>
        {% include "global/partials/messages.html" %}
    </div>
    <div class="gp-content">
        <div class="cards">
            <div class="card rendas">
                <h3>Rendas</h3>
                <span><i class="bi bi-cash-stack"></i> R$ {{ total_rendas.total }}</span>
            </div>
            <div class="card investimentos">
                <h3>Investimentos</h3>
                <span><i class="bi bi-graph-up"></i> R$ {{ total_investimentos.total }}</span>
            </div>
            <div class="card gastos">
                <h3>Gastos</h3>
                <span><i class="bi bi-credit-card-fill"></i> R$ {{ total_gastos.total }}</span>
            </div>
            <div class="card sem-track">
                <h3>Sem Lançamento</h3>
                <span><i class="bi bi-question-circle-fill"></i> R$ {{ sem_lancamento }}</span>
            </div>
        </div>
        <div class="vg-anno">
            <div class="annotations">
                <h2 class="table_title">Total de Rendas por Tipo</h2>
                <table class="">
                    <thead>
                        <tr>
                            <th>Tipo</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for tipo in annotations_rendas %}
                            <tr>
                                <td>{{ tipo.tipo__nome }}</td>
                                <td>R$ {{ tipo.total_por_tipo }}</td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td>Total</td>
                            <td>R$ {{ total_rendas.total }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="annotations">
                <h2 class="table_title">Total de Investimentos por Tipo</h2>
                <table class="">
                    <thead>
                        <tr>
                            <th>Tipo</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for tipo in annotations_invest.por_tipo %}
                            <tr>
                                <td>{{ tipo.tipo__nome }}</td>
                                <td>R$ {{ tipo.total_por_tipo }}</td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td>Total</td>
                            <td>R$ {{ total_investimentos.total }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="annotations">
                <h2 class="table_title">Total de Gastos por Tipo</h2>
                <table class="">
                    <thead>
                        <tr>
                            <th>Tipo</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for descricao in annotations_gastos.por_descricao %}
                            <tr>
                                <td>{{ descricao.descricao }}</td>
                                <td>R$ {{ descricao.total_por_descricao }}</td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td>Total</td>
                            <td>R$ {{ total_gastos.total }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="vg-bt-links">
        <a class="animated-link-black" href="{% url "dashboard:visao_geral" %}">Mês Atual</a>
        <a class="animated-link-black" href="{% url "dashboard:visao_geral_prox_mes" %}">Próximo Mês</a>
    </div>
</section>
{% endblock content %}
{% block scripts %}
<script src="{% static 'global/js/filter.js' %}"></script>
{% endblock scripts %}

dashboard/templates/dashboard/pages/visao_geral_prox_mes.html
{% extends 'global/base.html' %}
{% load static %}
{% block title %}Visão Geral{% endblock title %}
{% block content %}
<section class="content">
    <div class="content_header">
        <h1 class="title_hero">Visão geral - {{ mes }}/{{ ano }}</h1>
        {% include "global/partials/messages.html" %}
    </div>
    <div class="cards">
        <div class="card rendas">
            <h3>Rendas</h3>
            <span><i class="bi bi-cash-stack"></i> R$ {{ total_rendas.total }}</span>
        </div>
        <div class="card investimentos">
            <h3>Investimentos</h3>
            <span><i class="bi bi-graph-up"></i> R$ {{ total_investimentos.total }}</span>
        </div>
        <div class="card gastos">
            <h3>Gastos</h3>
            <span><i class="bi bi-credit-card-fill"></i> R$ {{ total_gastos.total }}</span>
        </div>
        <div class="card sem-track">
            <h3>Sem Lançamento</h3>
            <span><i class="bi bi-question-circle-fill"></i> R$ {{ sem_lancamento }}</span>
        </div>
    </div>
    <div class="charts">
        <div class="annotations">
            <h2 class="table_title">Total de Rendas por Tipo</h2>
            <table class="">
                <thead>
                    <tr>
                        <th>Tipo</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tipo in annotations_rendas %}
                        <tr>
                            <td>{{ tipo.tipo__nome }}</td>
                            <td>R$ {{ tipo.total_por_tipo }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td>Total</td>
                        <td>R$ {{ total_rendas.total }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="annotations">
            <h2 class="table_title">Total de Investimentos por Tipo</h2>
            <table class="">
                <thead>
                    <tr>
                        <th>Tipo</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tipo in annotations_invest.por_tipo %}
                        <tr>
                            <td>{{ tipo.tipo__nome }}</td>
                            <td>R$ {{ tipo.total_por_tipo }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td>Total</td>
                        <td>R$ {{ total_investimentos.total }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="annotations">
            <h2 class="table_title">Total de Gastos por Tipo</h2>
            <table class="">
                <thead>
                    <tr>
                        <th>Tipo</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for descricao in annotations_gastos.por_descricao %}
                        <tr>
                            <td>{{ descricao.descricao }}</td>
                            <td>R$ {{ descricao.total_por_descricao }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td>Total</td>
                        <td>R$ {{ total_gastos.total }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <a href="{% url "dashboard:visao_geral" %}">Mês Atual</a>
</section>
{% endblock content %}
{% block scripts %}
<script src="{% static 'global/js/filter.js' %}"></script>
{% endblock scripts %}