core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('home.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('rendas/', include('renda.urls')),
    path('investimentos/', include('investimento.urls')),
    path('gastos/', include('gasto.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.logout_view, name='logout'),
]

home/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.views import View

from users.forms import LoginForm, UserForm


class HomeView(View):
    def get(self, request):
        return render(request, 'home/pages/index.html')


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        ctx = {
            'form': form
        }
        return render(request, 'home/pages/login.html', ctx)

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            authenticated_user = authenticate(
                username=form.cleaned_data.get('username', ''),
                password=form.cleaned_data.get('password', ''),
            )

            if authenticated_user is not None:
                login(request, authenticated_user)
                messages.success(request, f'Bem vindo de volta {request.user}')
                return redirect("dashboard:index")

            messages.error(request, 'Credenciais Inválidas')
            return redirect("home:index")

        messages.error(request, 'Credenciais Inválidas')
        return redirect("home:index")


class RegisterView(View):
    def get(self, request):
        form = UserForm()
        ctx = {
            'form': form
        }
        return render(request, 'home/pages/register.html', ctx)

    def post(self, request):
        POST = request.POST
        request.session['register_form_data'] = POST
        form = UserForm(POST or None)

        if form.is_valid():
            data = form.save(commit=False)
            data.set_password(data.password)
            data.save()

            del (request.session['register_form_data'])
            messages.success(request, 'Usuário criado, por favor entre em sua conta')  # noqa
            return redirect('home:login')

        messages.error(request, 'Corrija os erros nos formulários')
        return render(request, 'home/pages/register.html', {
            "form": form
        })


@login_required(login_url='home:index', redirect_field_name='next')
def logout_view(request):
    if not request.POST:
        return redirect('home:index')

    if request.POST.get('username') != request.user.username:
        return redirect('home:index')

    logout(request)
    return redirect('home:index')

home/templates/home/pages/index.html
{% extends 'global/home.html' %}
{% block title %}Home{% endblock title %}
{% block content %}
<section id="home" class="section section-banner">
    <h1>Baner</h1>
</section>

<!-- Recursos -->
<section id="features" class="section section-features">
    <h1>Features</h1>
</section>

<!-- Como Funciona -->
<section id="how-it-works" class="section section-how-it-works">
    <h1>Como Funciona</h1>
</section>

<!-- Depoimentos -->
<section id="testimonials" class="section section-testimonials">
    <h1>Depoimentos</h1>
</section>

<!-- Preços -->
<section id="pricing" class="section section-pricing">
    <h1>Pricing</h1>
</section>

<!-- Contato -->
<section id="contact" class="section section-contact">
    <h1>Contato</h1>
</section>

<footer class="footer">
    <span>CapitalCare</span>
    <div class="links">
        <span>Desenvolvido por Philip Persan</span>
        <a href="">Linkedin</a>
        <a href="">GitHub</a>
    </div>
</footer>
{% endblock content %}

home/templates/home/pages/login.html
{% extends 'global/home.html' %}
{% block title %}Login{% endblock title %}
{% block content %}
<section id="login" class="section">
    <div class="form">
        <h1>Faça Login</h1>
        <form action="{% url 'home:login' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="form_group">
                <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                {{ field }}
            </div>
            {% endfor %}
            <button class="btn-p" type="submit">Entrar</button>
        </form>
    </div>
</section>
{% endblock content %}

home/templates/home/pages/register.html
{% extends 'global/home.html' %}
{% block title %}Register{% endblock title %}
{% block content %}
<section id="login" class="section">
    <div class="form">
        <h1>Criar Conta</h1>
        <form action="{% url 'home:register' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form_group">
                    <label for="{{field.id_for_label}}">{{field.label}}:</label>
                    {{ field }}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            {% endfor %}
            <button class="btn-p" type="submit">Entrar</button>
        </form>
    </div>
</section>
{% endblock content %}