core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('home.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('rendas/', include('renda.urls')),
    path('investimentos/', include('investimento.urls')),
    path('gastos/', include('gasto.urls')),
    path('admin/', admin.site.urls),
]

investimento/urls.py
from django.urls import path

from . import views

app_name = 'investimentos'

urlpatterns = [
    path(
        'api/v1/tipos_de_investimentos/',
        views.TipoInvestimentosAPIView.as_view(),
        name='api_tipo_invest'
    ),
    path(
        'api/v1/investimentos/',
        views.InvestimentosAPIView.as_view(),
        name='api_investimentos'
    ),
    path(
        'api/v1/agreggations/',
        views.InvestimentosAggregationAPIView.as_view(),
        name='api_agreggations'
    ),
    path(
        'api/v1/annotations/',
        views.InvestimentosAnnotationsAPIView.as_view(),
        name='api_annotations'
    ),
    path(
        'create/',
        views.InvestimentoCreateView.as_view(),
        name='investimentos_create'
    ),
    path(
        'list/',
        views.InvestimentosListView.as_view(),
        name='investimentos_list'
    ),
    path(
        'update/<int:id>/',
        views.InvestimentoUpdateView.as_view(),
        name='investimentos_update'
    ),
    path(
        'delete/<int:id>/',
        views.InvestimentoDeleteView.as_view(),
        name='investimentos_delete'
    ),
    path(
        'tipo/create/',
        views.TipoInvestimentoCreateView.as_view(),
        name='tipo_create'
    ),
    path(
        'tipo/delete/<int:id>/',
        views.TipoInvestimentoDeleteView.as_view(),
        name='tipo_delete'
    )
]

renda/urls.py
from django.urls import path

from . import views

app_name = 'rendas'

urlpatterns = [
    path(
        'api/v1/tipos_de_rendas/',
        views.TipoRendasAPIView.as_view(),
        name='api_list_tipos'
    ),
    path(
        'api/v1/rendas/',
        views.RendasAPIView.as_view(),
        name='api_list'
    ),
    path(
        'api/v1/agreggations/',
        views.RendasAgreggationsAPIView.as_view(),
        name='api_agreggations'
    ),
    path(
        'api/v1/annotations/',
        views.RendasAnnotationsAPIView.as_view(),
        name='api_annotations'
    ),
    path(
        'create/',
        views.RendasCreateView.as_view(),
        name='rendas_create'
    ),
    path(
        'list/',
        views.RendasListView.as_view(),
        name='rendas_list'
    ),
    path(
        'update/<int:id>/',
        views.RendasUpdateView.as_view(),
        name='rendas_update'
    ),
    path(
        'delete/<int:id>/',
        views.RendasDeleteView.as_view(),
        name='rendas_delete'
    ),
    path(
        'delete/tipo/<int:id>/',
        views.TipoRendasDeleteView.as_view(),
        name='tipo_rendas_delete'
    ),
]

investimento/models.py
from django.db import models

from users.models import User


class TipoInvestimento(models.Model):
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='User'
    )
    nome = models.CharField(
        verbose_name='Nome',
        max_length=50,
        unique=False,
        blank=False,
        null=False,
        default='Ações'
    )

    def __str__(self) -> str:
        return self.nome

    class Meta:
        verbose_name = 'Tipo de Investimento'
        verbose_name_plural = 'Tipos de Investimento'
        ordering = ['owner', 'nome']


class Investimento(models.Model):
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='User'
    )
    tipo = models.ForeignKey(
        TipoInvestimento,
        on_delete=models.SET_NULL,
        blank=False,
        null=True
    )
    valor = models.DecimalField(
        verbose_name='Valor',
        max_digits=11,
        decimal_places=2,
        blank=False,
        null=True
    )
    data = models.DateField(
        verbose_name='Data',
        auto_created=False
    )
    operacao = models.CharField(
        verbose_name='Tipo de Operação',
        max_length=50,
        blank=False,
        null=False,
        choices=(
            ('Compra', 'Compra'),
            ('Venda', 'Venda')
        ),
        default='Compra'
    )
    ativo = models.CharField(
        verbose_name='Ativo',
        max_length=10,
        blank=False,
        null=True,
    )
    obs = models.CharField(
        verbose_name='Observações',
        max_length=255,
        blank=True,
        null=False,
        default='Sem Obervações'
    )

    def __str__(self) -> str:
        return f'{self.tipo} - {self.data.strftime("%d/%m/%Y")}'

    class Meta:
        verbose_name = 'Investimento'
        verbose_name_plural = 'Investimentos'
        ordering = ['owner', '-data', 'tipo']

investimento/forms.py
from typing import Any

from django import forms

from .models import Investimento, TipoInvestimento
from .selectors import get_tipo_investimento_by_user


class TipoInvestimentoForm(forms.ModelForm):
    class Meta:
        model = TipoInvestimento
        fields = ['nome', ]


class InvestimentoForm(forms.ModelForm):

    class Meta:
        model = Investimento
        fields = [
            'tipo', 'valor',
            'data', 'operacao',
            'ativo', 'obs'
        ]

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)

        tipos_investimentos = get_tipo_investimento_by_user(request)
        self.fields['tipo'].queryset = tipos_investimentos

    def clean(self) -> dict[str, Any]:
        return super().clean()


class InvestimentoUpdateForm(forms.ModelForm):

    class Meta:
        model = Investimento
        fields = [
            'tipo', 'valor',
            'data', 'operacao',
            'ativo', 'obs'
        ]

    def clean(self) -> dict[str, Any]:
        return super().clean()

investimento/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from rest_framework.generics import ListAPIView
from rest_framework.permissions import IsAuthenticated

from .forms import (InvestimentoForm, InvestimentoUpdateForm,
                    TipoInvestimentoForm)
from .models import Investimento, TipoInvestimento
from .selectors import (get_aggregations_investimentos,
                        get_annotations_investimentos, get_investimento_by_id,
                        get_investimentos_by_user)
from .serializers import InvestimentoSerializer, TipoInvestSerializer


class TipoInvestimentosAPIView(ListAPIView):
    serializer_class = TipoInvestSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return TipoInvestimento.objects.filter(owner=self.request.user)


class InvestimentosAPIView(ListAPIView):
    serializer_class = InvestimentoSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return Investimento.objects.filter(
            owner=self.request.user
        ).select_related('tipo')


class InvestimentosListView(View):

    def get(self, request):
        investimentos = get_investimentos_by_user(request)
        annotations = get_annotations_investimentos(request)

        paginator = Paginator(investimentos, 15)
        page = request.GET.get('page')
        page_obj = paginator.get_page(page)

        valores = get_aggregations_investimentos(investimentos)

        ctx = {
            'page_obj': page_obj,
            'valores': valores,
            'annotations': annotations
        }
        return render(request, 'investimento/pages/list_investimentos.html', ctx)  # noqa


class InvestimentoUpdateView(View):

    def get(self, request, id):
        investimento = get_investimento_by_id(id)
        form_investimento = InvestimentoForm(request, instance=investimento)

        ctx = {
            'investimento': investimento,
            'form': form_investimento
        }

        return render(
            request,
            'investimento/pages/update_investimento.html',
            ctx
        )

    def post(self, request, id):
        investimento = get_investimento_by_id(id)
        form = InvestimentoUpdateForm(request.POST, instance=investimento)

        if form.is_valid():
            form.save()
            messages.success(
                request, f'Investimento {investimento} Alterado com Sucesso!'
            )
        else:
            messages.error(
                request, f'Erro ao salvar o Investimento {investimento}'
            )
        return redirect('investimentos:investimentos_list')


class InvestimentoCreateView(View):
    def get(self, request):
        form = InvestimentoForm(request)
        form_tipo = TipoInvestimentoForm()
        tipos = TipoInvestimento.objects.filter(
            owner=request.user
        )

        ctx = {
            'form': form,
            'form_tipo': form_tipo,
            'tipos': tipos
        }
        return render(request, 'investimento/pages/create_investimento.html', ctx)  # noqa

    def post(self, request):
        form = InvestimentoForm(request=request, data=request.POST)

        if form.is_valid():
            data = form.save(commit=False)
            data.owner = request.user
            data.save()

            messages.success(
                request, 'Investimento Criado com Sucesso!'
            )
            return redirect('investimentos:investimentos_create')


class InvestimentoDeleteView(View):
    def get(self, request, id):
        investimento = get_object_or_404(Investimento, id=id)

        ctx = {
            'investimento': investimento
        }

        return render(request, 'investimento/pages/delete_investimento.html', ctx)  # noqa

    def post(self, request, id):
        invest = request.POST.get('id')
        investimento = get_object_or_404(Investimento, id=invest)

        messages.success(
            request, f'Investimento {investimento} apagado com sucesso!')

        investimento.delete()

        return redirect('investimentos:investimentos_list')


class TipoInvestimentoCreateView(View):
    def post(self, request):
        form = TipoInvestimentoForm(request.POST or None)

        if form.is_valid():
            data = form.save(commit=False)
            data.owner = request.user
            data.save()
            messages.success(
                request,
                'Tipo de investimento criado!'
            )

        return redirect('investimentos:investimentos_create')


class TipoInvestimentoDeleteView(View):
    def get(self, request, id):
        tipo = get_object_or_404(TipoInvestimento, id=id)
        tipo.delete()
        messages.success(
            request,
            'Tipo de investimento apagado!'
        )
        return redirect('investimentos:investimentos_create')

investimento/views/api.py
from rest_framework.generics import ListAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from ..models import Investimento, TipoInvestimento
from ..selectors import (get_aggregations_investimentos,
                         get_annotations_investimentos,
                         get_investimentos_by_user)
from ..serializers import (InvestimentoPorAtivoSerializer,
                           InvestimentoPorOperacaoSerializer,
                           InvestimentoPorTipoSerializer,
                           InvestimentosAggregationsSerializer,
                           InvestimentoSerializer, TipoInvestSerializer)


class TipoInvestimentosAPIView(ListAPIView):
    serializer_class = TipoInvestSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return TipoInvestimento.objects.filter(owner=self.request.user)


class InvestimentosAPIView(ListAPIView):
    serializer_class = InvestimentoSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return Investimento.objects.filter(
            owner=self.request.user
        ).select_related('tipo')


class InvestimentosAggregationAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        investimentos = get_investimentos_by_user(request)
        agreggartions = get_aggregations_investimentos(investimentos)

        serializer = InvestimentosAggregationsSerializer(agreggartions)

        return Response(serializer.data)


class InvestimentosAnnotationsAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        annotations = get_annotations_investimentos(request)
        serializer = {
            'por_tipo': InvestimentoPorTipoSerializer(
                annotations['por_tipo'],
                many=True
            ).data,
            'por_ativo': InvestimentoPorAtivoSerializer(
                annotations['por_ativo'],
                many=True
            ).data,
            'por_operacao': InvestimentoPorOperacaoSerializer(
                annotations['por_operacao'],
                many=True
            ).data
        }
        return Response(serializer)

investimento/views/investimento.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View

from ..forms import (InvestimentoForm, InvestimentoUpdateForm,
                     TipoInvestimentoForm)
from ..models import Investimento, TipoInvestimento
from ..selectors import (get_aggregations_investimentos,
                         get_annotations_investimentos, get_investimento_by_id,
                         get_investimentos_by_user)


class InvestimentosListView(View):

    def get(self, request):
        investimentos = get_investimentos_by_user(request)
        annotations = get_annotations_investimentos(request)

        paginator = Paginator(investimentos, 15)
        page = request.GET.get('page')
        page_obj = paginator.get_page(page)

        valores = get_aggregations_investimentos(investimentos)

        ctx = {
            'page_obj': page_obj,
            'valores': valores,
            'annotations': annotations
        }
        return render(request, 'investimento/pages/list_investimentos.html', ctx)  # noqa


class InvestimentoUpdateView(View):

    def get(self, request, id):
        investimento = get_investimento_by_id(id)
        form_investimento = InvestimentoForm(request, instance=investimento)

        ctx = {
            'investimento': investimento,
            'form': form_investimento
        }

        return render(
            request,
            'investimento/pages/update_investimento.html',
            ctx
        )

    def post(self, request, id):
        investimento = get_investimento_by_id(id)
        form = InvestimentoUpdateForm(request.POST, instance=investimento)

        if form.is_valid():
            form.save()
            messages.success(
                request, f'Investimento {investimento} Alterado com Sucesso!'
            )
        else:
            messages.error(
                request, f'Erro ao salvar o Investimento {investimento}'
            )
        return redirect('investimentos:investimentos_list')


class InvestimentoCreateView(View):
    def get(self, request):
        form = InvestimentoForm(request)
        form_tipo = TipoInvestimentoForm()
        tipos = TipoInvestimento.objects.filter(
            owner=request.user
        )

        ctx = {
            'form': form,
            'form_tipo': form_tipo,
            'tipos': tipos
        }
        return render(request, 'investimento/pages/create_investimento.html', ctx)  # noqa

    def post(self, request):
        form = InvestimentoForm(request=request, data=request.POST)

        if form.is_valid():
            data = form.save(commit=False)
            data.owner = request.user
            data.save()

            messages.success(
                request, 'Investimento Criado com Sucesso!'
            )
            return redirect('investimentos:investimentos_create')


class InvestimentoDeleteView(View):
    def get(self, request, id):
        investimento = get_object_or_404(Investimento, id=id)

        ctx = {
            'investimento': investimento
        }

        return render(request, 'investimento/pages/delete_investimento.html', ctx)  # noqa

    def post(self, request, id):
        invest = request.POST.get('id')
        investimento = get_object_or_404(Investimento, id=invest)

        messages.success(
            request, f'Investimento {investimento} apagado com sucesso!')

        investimento.delete()

        return redirect('investimentos:investimentos_list')

investimento/views/tipo_investimento.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.views import View

from ..forms import TipoInvestimentoForm
from ..models import TipoInvestimento


class TipoInvestimentoCreateView(View):
    def post(self, request):
        form = TipoInvestimentoForm(request.POST or None)

        if form.is_valid():
            data = form.save(commit=False)
            data.owner = request.user
            data.save()
            messages.success(
                request,
                'Tipo de investimento criado!'
            )

        return redirect('investimentos:investimentos_create')


class TipoInvestimentoDeleteView(View):
    def get(self, request, id):
        tipo = get_object_or_404(TipoInvestimento, id=id)
        tipo.delete()
        messages.success(
            request,
            'Tipo de investimento apagado!'
        )
        return redirect('investimentos:investimentos_create')

investimento/templates/investimento/pages/create_investimento.html
{% extends 'global/base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static "css/investimentos.css" %}">
{% endblock style %}
{% block title %}Invesitmentos{% endblock title %}
{% block content %}
<section>
    <h1>Criar Invesitmento</h1>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <span class="{{ message.tags }}">{{ message }}</span>
            {% endfor %}
        </div>
    {% endif %}
    <div class="edit_investimentos">
        <h2 class="table_title">Criar Investimento</h2>
        <form action="{% url "investimentos:investimentos_create" %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ request.user }}">
            {% for field in form %}
                <div class="form_group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                    {{ field }}
                </div>
            {% endfor %}
            <button type="submit">Salvar</button>
            <a href="{% url "investimentos:investimentos_list" %}">Voltar</a>
        </form>
    </div>
    <div class="edit_investimentos">
        <h2 class="table_title">Criar Tipo de Investimento</h2>
        <form action="{% url "investimentos:tipo_create" %}" method="post">
            {% csrf_token %}
            {% for field in form_tipo %}
                <div class="form_group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                    {{ field }}
                </div>
            {% endfor %}
            <button type="submit">Salvar</button>
        </form>
        <ul>
            {% for tipo in tipos %}
                <li>{{ tipo }} <a href="{% url "investimentos:tipo_delete" tipo.id %}"><i class="bi bi-x-circle-fill"></i></a></li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock content %}
{% block scripts %}
<script src="{% static 'global/js/dropdowns.js' %}"></script>
<script src="{% static 'global/js/filter.js' %}"></script>
{% endblock scripts %}

investimento/templates/investimento/pages/delete_investimento.html
{% extends 'global/base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static "css/investimentos.css" %}">
{% endblock style %}
{% block title %}Invesitmentos{% endblock title %}
{% block content %}
<section>
    <h1>Apagar Invesitmento</h1>
    <h1>{{ investimento }}</h1>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <span class="{{ message.tags }}">{{ message }}</span>
            {% endfor %}
        </div>
    {% endif %}
    <div class="edit_investimentos">
        <h2 class="table_title">Apagar Investimento?</h2>
        <ul>
            <li>Tipo: {{ investimento.tipo }}</li>
            <li>Valor: R$ {{ investimento.valor }}</li>
            <li>Data: {{ investimento.data|date:"SHORT_DATE_FORMAT" }}</li>
            <li>Operação: {{ investimento.operacao }}</li>
            <li>Ativo: {{ investimento.ativo }}</li>
            <li>Observação: {{ investimento.obs }}</li>
        </ul>
        <form action="{% url "investimentos:investimentos_delete" investimento.id %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="user" value="{{ request.user }}">
            <input type="hidden" name="id" value="{{ investimento.id }}">
            <button type="submit">Apagar</button>
            <a href="{% url "investimentos:investimentos_list" %}">Voltar</a>
        </form>
    </div>
</section>
{% endblock content %}
{% block scripts %}
<script src="{% static 'global/js/dropdowns.js' %}"></script>
<script src="{% static 'global/js/filter.js' %}"></script>
{% endblock scripts %}

investimento/templates/investimento/pages/list_investimentos.html
{% extends 'global/base.html' %}
{% load static %}
{% block title %}Invesitmentos{% endblock title %}
{% block content %}
<section>
    <h1>Lista de Invesitmentos</h1>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <span class="{{ message.tags }}">{{ message }}</span>
            {% endfor %}
        </div>
    {% endif %}
    <div class="filters">
        <h1>Filtros<button id="btn-filter"><i class="bi bi-filter-square-fill icon"></i></button></h1>

        <form id="form-filter" action="{% url "rendas:rendas_list" %}" method="get">
            {% csrf_token %}
            {% for field in filters.form %}
                <div class="form_group">
                    <label for="{{field.id_for_label}}">{{field.label}}:</label>
                    {{ field }}
                </div>
            {% endfor %}
            <div class="btns">
                <button class="btn-s" type="submit">Filtrar</button>
                <a class="btn-s" href="{% url "rendas:rendas_list" %}">Limpar</a>
            </div>
        </form>
    </div>
    <div class="cards">
        <div class="card">
            <h3>Total</h3>
            <span>R$ {{ valores.total }}</span>
        </div>
        <div class="card">
            <h3>Média</h3>
            <span>R$ {{ valores.avg|floatformat:2 }}</span>
        </div>
        <div class="card">
            <h3>Menor</h3>
            <span>R$ {{ valores.min }}</span>
        </div>
        <div class="card">
            <h3>Maior</h3>
            <span>R$ {{ valores.max }}</span>
        </div>
    </div>
    <div class="tables">
        <div class="list_investimentos">
            <h2 class="table_title">Investimentos</h2>
            <table class="">
                <thead>
                    <tr>
                        <th>Data</th>
                        <th>Tipo</th>
                        <th>Valor</th>
                        <th>Operação</th>
                        <th>Ativo</th>
                        <th>Observação</th>
                        <th>Opções</th>
                    </tr>
                </thead>
                <tbody>
                    {% for invest in page_obj %}
                    <tr>
                        <td>{{ invest.data|date:"SHORT_DATE_FORMAT" }}</td>
                        <td>{{ invest.tipo }}</td>
                        <td>R$ {{ invest.valor }}</td>
                        <td>{{ invest.operacao }}</td>
                        <td>{{ invest.ativo }}</td>
                        <td>{{ invest.obs }}</td>
                        <td class="actions">
                            <a href="{% url "investimentos:investimentos_delete" invest.id %}"><i class="bi bi-x-circle-fill"></i></a>
                            <a href="{% url "investimentos:investimentos_update" invest.id %}"><i class="bi bi-pen-fill"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% include "global/partials/pagination.html" %}
        </div>
        <div class="annotations">
            <div class="list_investimentos">
                <h2 class="table_title">Investimentos por Tipo</h2>
                <table class="">
                    <thead>
                        <tr>
                            <th>Tipo</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for tipo in annotations.por_tipo %}
                        <tr>
                            <td>{{ tipo.tipo__nome }}</td>
                            <td>R$ {{ tipo.total_por_tipo }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            
            <div class="list_investimentos">
                <h2 class="table_title">Investimentos por Ativo</h2>
                <table class="">
                    <thead>
                        <tr>
                            <th>Ativo</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ativo in annotations.por_ativo %}
                        <tr>
                            <td>{{ ativo.ativo }}</td>
                            <td>R$ {{ ativo.total_por_ativo }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            
            <div class="list_investimentos">
                <h2 class="table_title">Investimentos por Operação</h2>
                <table class="">
                    <thead>
                        <tr>
                            <th>Operação</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for operacao in annotations.por_operacao %}
                        <tr>
                            <td>{{ operacao.operacao }}</td>
                            <td>R$ {{ operacao.total_por_operacao }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock content %}
{% block scripts %}
<script src="{% static 'global/js/dropdowns.js' %}"></script>
<script src="{% static 'global/js/filter.js' %}"></script>
{% endblock scripts %}

investimento/templates/investimento/pages/update_investimento.html
{% extends 'global/base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static "css/investimentos.css" %}">
{% endblock style %}
{% block title %}Invesitmentos{% endblock title %}
{% block content %}
<section>
    <h1>Editar de Invesitmento</h1>
    <h1>{{ investimento }}</h1>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <span class="{{ message.tags }}">{{ message }}</span>
            {% endfor %}
        </div>
    {% endif %}
    <div class="edit_investimentos">
        <h2 class="table_title">Editar Investimento</h2>
        <form action="{% url "investimentos:investimentos_update" investimento.id %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ request.user }}">
            {% for field in form %}
                <div class="form_group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                    {{ field }}
                </div>
            {% endfor %}
            <button type="submit">Salvar</button>
            <a href="{% url "investimentos:investimentos_list" %}">Voltar</a>
        </form>
    </div>
</section>
{% endblock content %}
{% block scripts %}
<script src="{% static 'global/js/dropdowns.js' %}"></script>
<script src="{% static 'global/js/filter.js' %}"></script>
{% endblock scripts %}