core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('home.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('rendas/', include('renda.urls')),
    path('investimentos/', include('investimento.urls')),
    path('gastos/', include('gasto.urls')),
    path('admin/', admin.site.urls),
]

renda/urls.py
from django.urls import path

from . import views

app_name = 'rendas'

urlpatterns = [
    path(
        'api/v1/tipos_de_rendas/',
        views.TipoRendasAPIView.as_view(),
        name='api_list_tipos'
    ),
    path(
        'api/v1/rendas/',
        views.RendasAPIView.as_view(),
        name='api_list'
    ),
    path(
        'api/v1/agreggations/',
        views.RendasAgreggationsAPIView.as_view(),
        name='api_agreggations'
    ),
    path(
        'api/v1/annotations/',
        views.RendasAnnotationsAPIView.as_view(),
        name='api_annotations'
    ),
    path(
        'create/',
        views.RendasCreateView.as_view(),
        name='rendas_create'
    ),
    path(
        'list/',
        views.RendasListView.as_view(),
        name='rendas_list'
    ),
    path(
        'update/<int:id>/',
        views.RendasUpdateView.as_view(),
        name='rendas_update'
    ),
    path(
        'delete/<int:id>/',
        views.RendasDeleteView.as_view(),
        name='rendas_delete'
    ),
    path(
        'delete/tipo/<int:id>/',
        views.TipoRendasDeleteView.as_view(),
        name='tipo_rendas_delete'
    ),
]

renda/models.py
from django.db import models

from users.models import User


class TipoRenda(models.Model):
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='User'
    )
    nome = models.CharField(
        verbose_name='Nome',
        max_length=50,
        unique=False,
        blank=False,
        null=False,
        default='Salário'
    )

    def __str__(self) -> str:
        return self.nome

    class Meta:
        verbose_name = 'Tipo de Renda'
        verbose_name_plural = 'Tipos de Renda'
        ordering = ['owner', 'nome']
        unique_together = ('owner', 'nome')


class Renda(models.Model):
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='User'
    )
    tipo = models.ForeignKey(
        TipoRenda,
        on_delete=models.SET_NULL,
        blank=False,
        null=True
    )
    valor = models.DecimalField(
        verbose_name='Valor',
        max_digits=11,
        decimal_places=2,
        blank=False,
        null=True
    )
    data = models.DateField(
        verbose_name='Data',
        auto_created=False
    )

    def __str__(self) -> str:
        return f'{self.tipo} - {self.data.strftime("%d/%m/%Y")}'

    class Meta:
        verbose_name = 'Renda'
        verbose_name_plural = 'Rendas'
        ordering = ['owner', '-data']

renda/forms.py
from django import forms

from .models import Renda, TipoRenda
from .selectors.tipo_rendas import get_tipos_by_user


class TipoRendaForm(forms.ModelForm):
    class Meta:
        model = TipoRenda
        fields = ['nome', ]


class RendaForm(forms.ModelForm):

    class Meta:
        model = Renda
        fields = ['tipo', 'valor', 'data']

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)

        tipos_renda = get_tipos_by_user(request)
        self.fields['tipo'].queryset = tipos_renda

renda/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.views import View
from rest_framework.generics import ListAPIView
from rest_framework.permissions import IsAuthenticated

from .filters import RendasFilter
from .forms import RendaForm, TipoRendaForm
from .models import Renda, TipoRenda
from .selectors import (get_aggregations_rendas, get_annotations_rendas,
                        get_rendas_by_id, get_rendas_by_user, get_tipo_by_id,
                        get_tipos_by_user)
from .serializers import RendaSerializer, TipoRendaSerializer
from .services import rendas_create, rendas_delete, rendas_update


class TipoRendasAPIView(ListAPIView):
    serializer_class = TipoRendaSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return TipoRenda.objects.filter(owner=self.request.user)


class RendasAPIView(ListAPIView):
    serializer_class = RendaSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return Renda.objects.filter(
            owner=self.request.user
        ).select_related('tipo')


class RendasListView(View):

    def get(self, request):
        rendas = get_rendas_by_user(request)
        filter = RendasFilter(request.GET, queryset=rendas)
        rendas = filter.qs

        annotations = get_annotations_rendas(request)

        paginator = Paginator(rendas, 15)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        valores = get_aggregations_rendas(rendas)

        ctx = {
            'page_obj': page_obj,
            'valores': valores,
            'filters': filter,
            'annotations': annotations
        }
        return render(request, 'renda/pages/list_rendas.html', ctx)


class RendasCreateView(View):

    def get(self, request):
        form_renda = RendaForm(request)
        form_tipo_renda = TipoRendaForm()
        tipos_renda = get_tipos_by_user(request)
        ctx = {
            'form_renda': form_renda,
            'form_tipo_renda': form_tipo_renda,
            'tipos_renda': tipos_renda
        }
        return render(request, 'renda/pages/create_rendas.html', ctx)

    def post(self, request):
        POST = request.POST
        model = POST.get('model')

        if model == 'create_renda':
            rendas_create(request)
        else:
            form = TipoRendaForm(POST or None)
            if form.is_valid():
                tipo_renda = form.save(commit=False)
                tipo_renda.owner = request.user
                tipo_renda.save()

        return redirect('rendas:rendas_create')


class TipoRendasDeleteView(View):
    def get(self, request, id):
        tipo = get_tipo_by_id(id)
        tipo.delete()
        messages.success(request, 'Tipo de Renda Apagado com Sucesso!')
        return redirect('rendas:rendas_create')


class RendasDeleteView(View):
    def get(self, request, id):
        rendas_delete(request, id)
        return redirect('rendas:rendas_list')


class RendasUpdateView(View):
    def get(self, request, id):
        renda = get_rendas_by_id(request, id)
        form = RendaForm(instance=renda, request=request)
        ctx = {
            'renda': renda,
            'form': form
        }
        return render(request, 'renda/pages/update_rendas.html', ctx)

    def post(self, request, id):
        renda = get_rendas_by_id(request, id)
        rendas_update(request, renda)
        return redirect('rendas:rendas_list')

renda/views/api.py
from rest_framework.generics import ListAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from ..models import Renda, TipoRenda
from ..selectors import (get_aggregations_rendas, get_annotations_rendas,
                         get_rendas_by_user)
from ..serializers import (RendasAggregationsSerializer, RendaSerializer,
                           RendasPorTipoSerializer, TipoRendaSerializer)


class TipoRendasAPIView(ListAPIView):
    serializer_class = TipoRendaSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return TipoRenda.objects.filter(owner=self.request.user)


class RendasAPIView(ListAPIView):
    serializer_class = RendaSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return Renda.objects.filter(
            owner=self.request.user
        ).select_related('tipo')


class RendasAgreggationsAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        rendas = get_rendas_by_user(request)
        agreggations = get_aggregations_rendas(rendas)
        serializer = RendasAggregationsSerializer(agreggations)

        return Response(serializer.data)


class RendasAnnotationsAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        annotations = get_annotations_rendas(request)
        serializer = RendasPorTipoSerializer(annotations, many=True)

        return Response(serializer.data)

renda/views/renda.py
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.views import View

from ..filters import RendasFilter
from ..forms import RendaForm, TipoRendaForm
from ..selectors import (get_aggregations_rendas, get_annotations_rendas,
                         get_rendas_by_id, get_rendas_by_user,
                         get_tipos_by_user)
from ..services import (rendas_create, rendas_delete,
                        rendas_per_month_plotly_bar,
                        rendas_per_month_type_plotly_bar, rendas_update)


class RendasListView(View):

    def get(self, request):
        rendas = get_rendas_by_user(request)
        filter = RendasFilter(request.GET, queryset=rendas)
        rendas = filter.qs

        chart1 = rendas_per_month_plotly_bar(rendas)
        chart2 = rendas_per_month_type_plotly_bar(rendas)
        annotations = get_annotations_rendas(request)

        paginator = Paginator(rendas, 8)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        valores = get_aggregations_rendas(rendas)

        ctx = {
            'page_obj': page_obj,
            'valores': valores,
            'filters': filter,
            'annotations': annotations,
            'chart1': chart1,
            'chart2': chart2
        }
        return render(request, 'renda/pages/list_rendas.html', ctx)


class RendasCreateView(View):

    def get(self, request):
        form_renda = RendaForm(request)
        form_tipo_renda = TipoRendaForm()
        tipos_renda = get_tipos_by_user(request)
        ctx = {
            'form_renda': form_renda,
            'form_tipo_renda': form_tipo_renda,
            'tipos_renda': tipos_renda
        }
        return render(request, 'renda/pages/create_rendas.html', ctx)

    def post(self, request):
        POST = request.POST
        model = POST.get('model')

        if model == 'create_renda':
            rendas_create(request)
        else:
            form = TipoRendaForm(POST or None)
            if form.is_valid():
                tipo_renda = form.save(commit=False)
                tipo_renda.owner = request.user
                tipo_renda.save()

        return redirect('rendas:rendas_create')


class RendasDeleteView(View):
    def get(self, request, id):
        rendas_delete(request, id)
        return redirect('rendas:rendas_list')


class RendasUpdateView(View):
    def get(self, request, id):
        renda = get_rendas_by_id(request, id)
        form = RendaForm(instance=renda, request=request)
        ctx = {
            'renda': renda,
            'form': form
        }
        return render(request, 'renda/pages/update_rendas.html', ctx)

    def post(self, request, id):
        renda = get_rendas_by_id(request, id)
        rendas_update(request, renda)
        return redirect('rendas:rendas_list')

renda/views/tipo_renda.py
from django.contrib import messages
from django.shortcuts import redirect
from django.views import View

from ..selectors import get_tipo_by_id


class TipoRendasDeleteView(View):
    def get(self, request, id):
        tipo = get_tipo_by_id(id)
        tipo.delete()
        messages.success(request, 'Tipo de Renda Apagado com Sucesso!')
        return redirect('rendas:rendas_create')

renda/templates/renda/pages/create_rendas.html
{% extends 'global/base.html' %}
{% load static %}
{% block title %}Criar Renda{% endblock title %}
{% block content %}
<section class="section_container">
    <div class="content_header">
        <h1 class="title_hero">Criar Renda</h1>
        {% include "global/partials/messages.html" %}
    </div>
    <div class="create_objects">
        <div class="form_create pd-bg-sh">
            <h1>Criar Renda</h1>
            <form action="{% url "rendas:rendas_create" %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="model" value="create_renda">
                {% for field in form_renda %}
                <div class="form_group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                    {{ field }}
                </div>
                {% endfor %}
                <button class="btn-s" type="submit">Criar</button>
            </form>
        </div>
        <div class="form_create pd-bg-sh">
            <h1>Criar Tipo de Renda</h1>
            <form action="" method="post">
                {% csrf_token %}
                <input type="hidden" name="model" value="create_tipo_renda">
                {% for field in form_tipo_renda %}
                <div class="form_group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                    {{ field }}
                </div>
                {% endfor %}
                <button class="btn-s" type="submit">Criar</button>
            </form>
            <h2>Tipos de Renda</h2>
            <div class="tipos">
                <ul>
                    {% for tipo in tipos_renda %}
                        <li>{{tipo.nome}} <a href="{% url "rendas:tipo_rendas_delete" tipo.id %}"><i class="bi bi-x-circle-fill"></i></a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</section>
{% endblock content %}
{% block scripts %}

{% endblock scripts %}

renda/templates/renda/pages/list_rendas.html
{% extends 'global/base.html' %}
{% load static %}
{% block title %}Rendas{% endblock title %}
{% block content %}
<section class="section_container">
    <div class="content_header">
        <h1 class="title_hero">Lista de Rendas</h1>
        {% include "global/partials/messages.html" %}
    </div>
    {% comment %} <div class="cards">
        <div class="card">
            <h3>Total</h3>
            <span>R$ {{ valores.total }}</span>
        </div>
        <div class="card">
            <h3>Média</h3>
            <span>R$ {{ valores.avg|floatformat:2 }}</span>
        </div>
        <div class="card">
            <h3>Menor</h3>
            <span>R$ {{ valores.min }}</span>
        </div>
        <div class="card">
            <h3>Maior</h3>
            <span>R$ {{ valores.max }}</span>
        </div>
    </div> {% endcomment %}
    <div class="list_section">
        <div class="chart1_list">
            {{ chart1|safe }}
        </div>
        <div class="chart2_list">
            {{ chart2|safe }}
        </div>
        <div class="filters">
            <h1>Filtros</h1>
            <form id="form-filter" action="{% url "rendas:rendas_list" %}" method="get">
                {% csrf_token %}
                {% for field in filters.form %}
                    <div class="form_group">
                        <label for="{{field.id_for_label}}">{{field.label}}:</label>
                        {{ field }}
                    </div>
                {% endfor %}
                <div class="btns">
                    <button class="btn-s" type="submit">Filtrar</button>
                    <a class="btn-s" href="{% url "rendas:rendas_list" %}">Limpar</a>
                </div>
            </form>
        </div>
        <div class="tables">
            <div class="list_investimentos">
                <h2 class="table_title">Rendas</h2>
                <table class="">
                    <thead>
                        <tr>
                            <th>Data</th>
                            <th>Tipo</th>
                            <th>Valor</th>
                            <th>Opções</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for rend in page_obj %}
                        <tr>
                            <td>{{ rend.data|date:"SHORT_DATE_FORMAT" }}</td>
                            <td>{{ rend.tipo }}</td>
                            <td>R$ {{ rend.valor }}</td>
                            <td class="actions">
                                <a href="{% url "rendas:rendas_delete" rend.id %}"><i class="bi bi-x-circle-fill"></i></a>
                                <a href="{% url "rendas:rendas_update" rend.id %}"><i class="bi bi-pen-fill"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% include "global/partials/pagination.html" %}
            </div>
            <div class="annotations">
                <h2 class="table_title">Total de Rendas por Tipo</h2>
                <table class="">
                    <thead>
                        <tr>
                            <th>Tipo</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for tipo in annotations %}
                        <tr>
                            <td>{{ tipo.tipo__nome }}</td>
                            <td>R$ {{ tipo.total_por_tipo }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock content %}
{% block scripts %}
{% endblock scripts %}

renda/templates/renda/pages/update_rendas.html
{% extends 'global/base.html' %}
{% load static %}
{% block title %}Atualizar Renda{% endblock title %}
{% block content %}
<section>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <span class="{{ message.tags }}">{{ message }}</span>
            {% endfor %}
        </div>
    {% endif %}
    <div class="form_renda">
        <h1>Atualizar Renda</h1>
        <form action="{% url "rendas:rendas_update" renda.id %}" method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="form_group">
                <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                {{ field }}
            </div>
            {% endfor %}
            <button class="btn-s" type="submit">Salvar</button>
        </form>
    </div>
</section>
{% endblock content %}
{% block scripts %}
<script src="{% static 'global/js/dropdowns.js' %}"></script>
{% endblock scripts %}